name: Upload to S3 on Push

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Specify the branch here
    paths:
      - '**/*.html'      # Trigger the workflow for any .html files changes
      - 'images/**'      # Trigger the workflow for any changes in the images directory
env:
  BUCKET_NAME: "${{ secrets.BUCKET_NAME }}"
  AWS_REGION: "${{ vars.AWS_REGION }}"
  GITHUB_REF: "master"
  CLOUDFRONT_DISTRIBUTION_ID: "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"  
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::064195113262:role/github-actions-role
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync repository to S3
      run: |
        aws s3 sync . s3://${{ env.BUCKET_NAME }} --exclude "node_modules/**" --exclude ".git/**" --exclude "dist/**" --exclude ".github/**" --exclude "README.md" --exclude "tf/**"
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
